### ISSUE TITLE
scene transitions

### ISSUE THREAD

**Issue by rafaelcastrocouto** [spicylobstergames/shotcaller-godot#127]
add an animation between scenes https://docs.godotengine.org/en/stable/classes/class_tween.html?highlight=tween

**Comment by bpodrygajlo** [comment]
The only scene transition I am aware of is between menu and the game map. Is there others? Would a simple fade-to-black and back suffice?

**Comment by rafaelcastrocouto** [comment]
yes the typical cutout with a black circle

**Comment by bpodrygajlo** [comment]
Added two transitions https://github.com/spicylobstergames/shotcaller-godot/pull/145


https://user-images.githubusercontent.com/16952886/201533426-39e8fbdd-cfeb-4586-9500-388431fcfa1c.mp4
