### ISSUE TITLE
Move Minimap to ScrollContainer

### ISSUE THREAD

**Issue by TheDuriel** [spicylobstergames/shotcaller-godot#185]
Replace current clipping method.

**Comment by rafaelcastrocouto** [comment]
testing performance (windows built)
[Shotcaller_win_debug_test.zip](https://github.com/spicylobstergames/shotcaller-godot/files/10860958/Shotcaller_win_debug_test.zip)

**Comment by rafaelcastrocouto** [comment]
not possible because of the fog of war lightining system
