### ISSUE TITLE
Not playable on case sensitive file system

### ISSUE THREAD

**Issue by Affinator** [spicylobstergames/shotcaller-godot#193]
Hi,
I am not able to start the project since all files use lowercase names, but are referenced via names with a capital letter at the beginning (i.e. Unit.gd in the scripts is called unit.gd on disk).

Is there any easy way to repair this without going through all the scripts and fixing references?

**Comment by rafaelcastrocouto** [comment]
I've updated all files and (hopefully) it should work everywhere now.

For those who want to avoid repeating my mistake, use this command in the local repository folder to be sure git won't ignore uppercase:
`git config --local core.ignorecase false` 

Please let me know if the PR https://github.com/spicylobstergames/shotcaller-godot/pull/194 really solved so I can close the issue.
