### ISSUE TITLE
Restart / end game screen

### ISSUE THREAD

**Issue by rafaelcastrocouto** [spicylobstergames/shotcaller-godot#57]
After destroying the castle the game needs to show the scoreboard* (todo) and reset everything to allow a new game to start. The restart game menu should be placed on the mid container on the game UI panels.

**Comment by bpodrygajlo** [comment]
I'll try this one.

**Comment by bpodrygajlo** [comment]
https://github.com/spicylobstergames/shotcaller-godot/pull/73
